import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Kanban.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Kanban-board</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <header className={styles.header}></header>
      <main className={styles.main}></main>
      <footer className={styles.footer}></footer>
    </div>

  )
}

export default Home
